FROM ghcr.io/astral-sh/uv:python3.12-trixie-slim

# Copy all files
COPY . .

# Install dependencies from pyproject.toml
RUN uv sync

EXPOSE 5000

# Start viusalisation server
ENTRYPOINT [ "uv", "run", "main.py" ]